package punchr;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marisa Treadway 
 */
public class HOME_Staff_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form HOME_JFrame
     */
    public HOME_Staff_JFrame() {
        initComponents();
        this.getRootPane().setDefaultButton(jButton_Submit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_upper = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabel_Welcome = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel_lower = new javax.swing.JPanel();
        jTextField_Input = new javax.swing.JTextField();
        jButton_Submit = new javax.swing.JButton();
        jButton_Logout = new javax.swing.JButton();
        jLabel_Input = new javax.swing.JLabel();
        jLabel_Results = new javax.swing.JLabel();
        jTextField_Results = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_upper.setBackground(new java.awt.Color(248, 148, 6));
        jPanel_upper.setToolTipText("");

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabel_Welcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Welcome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Welcome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Welcome.setText("Punchr Staff Dashboard");

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_upperLayout = new javax.swing.GroupLayout(jPanel_upper);
        jPanel_upper.setLayout(jPanel_upperLayout);
        jPanel_upperLayout.setHorizontalGroup(
            jPanel_upperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_upperLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel_Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_upperLayout.setVerticalGroup(
            jPanel_upperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Welcome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_upperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_upperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMin, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGroup(jPanel_upperLayout.createSequentialGroup()
                        .addComponent(jLabelClose)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel_lower.setBackground(new java.awt.Color(44, 62, 80));

        jTextField_Input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton_Submit.setBackground(new java.awt.Color(34, 167, 240));
        jButton_Submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Submit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Submit.setText("Submit");
        jButton_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SubmitActionPerformed(evt);
            }
        });

        jButton_Logout.setBackground(new java.awt.Color(255, 0, 51));
        jButton_Logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Logout.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Logout.setText("Logout");
        jButton_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogoutActionPerformed(evt);
            }
        });

        jLabel_Input.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_Input.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Input.setText("Input codes here:");

        jLabel_Results.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_Results.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Results.setText("Results display here:");

        javax.swing.GroupLayout jLabel_lowerLayout = new javax.swing.GroupLayout(jLabel_lower);
        jLabel_lower.setLayout(jLabel_lowerLayout);
        jLabel_lowerLayout.setHorizontalGroup(
            jLabel_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabel_lowerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLabel_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLabel_lowerLayout.createSequentialGroup()
                        .addComponent(jLabel_Results, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jLabel_lowerLayout.createSequentialGroup()
                        .addComponent(jLabel_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLabel_lowerLayout.createSequentialGroup()
                        .addGroup(jLabel_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Results, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLabel_lowerLayout.createSequentialGroup()
                                .addComponent(jTextField_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jButton_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jLabel_lowerLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))))
        );
        jLabel_lowerLayout.setVerticalGroup(
            jLabel_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabel_lowerLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLabel_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel_Results, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Results, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_upper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_lower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_upper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_lower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogoutActionPerformed
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_LogoutActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jButton_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SubmitActionPerformed
        String input = jTextField_Input.getText();
        int length = input.length();
        
        switch (length) {
            case 6:
                checkAccounts(input);
                jTextField_Input.setText("");
                break;
            case 8:
                checkRewards(input);
                break;
            default:
                jTextField_Results.setText("Invalid code - not the right length");
                break;
        }
        
            
    }//GEN-LAST:event_jButton_SubmitActionPerformed

    public void checkAccounts(String punchCode)
    {
        PreparedStatement ps;
        ResultSet rs;
        String query = "SELECT * FROM `accounts` WHERE `punchcode` =?";
        try 
        {
            ps = MyConnection.getConnection().prepareStatement(query, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ps.setString(1, punchCode);
            rs = ps.executeQuery();
            
            
            if(rs.next()) //if a record is found
            {
                int punchcount = rs.getInt("punchcount");
                String bday = null;
                if (rs.getDate("birthdate") != null)
                {   SimpleDateFormat dateformat = new SimpleDateFormat("MM-dd");
                    bday = dateformat.format(rs.getDate("birthdate"));}
                rs.updateInt("punchcount", (punchcount + 1));
                rs.updateRow();
                updateRewards(punchCode, rs.getInt("punchcount"), bday); //checks all (10) rewards to see if availability has changed
                 jTextField_Results.setText("Punch count has been updated inform user to refresh acct");
            }
            else 
                { jTextField_Results.setText("Invalid code - Punch Code is not in our system.");}

            
        } catch (SQLException ex) 
            {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }

    }
    
    public void updateRewards(String punchCode, int punchcount, String birthday)
    {
        PreparedStatement ps;
        ResultSet rs;
        String query = "SELECT * FROM `rewards` WHERE `punchcode` =?";
        
        try 
        {
            ps = MyConnection.getConnection().prepareStatement(query, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ps.setString(1, punchCode);
            rs = ps.executeQuery();
            int i = 0;
            
            while(rs.next()) //if records are found
                {
                    i++;
                    int punchesrequired = rs.getInt("punchesrequired");

                    if (punchesrequired == punchcount)
                    {
                        rs.updateInt("available", 1);
                        rs.updateRow();
                        //Testing: System.out.print("row updated-- available = 1\n");

                    }
                    SimpleDateFormat dateformat = new SimpleDateFormat("MM-dd");
                    Calendar now = Calendar.getInstance();
                    now.set(Calendar.HOUR_OF_DAY, 0);
                    //String today = now.toString();
                    String today = dateformat.format(now.getTime());
                    if (birthday != null && birthday.equals(today) && rs.getInt("used") != 1 && rs.getInt("show_code") != 1 && rs.getString("description").equals("Birthday reward 25% off total bill"))
                    {
                        rs.updateInt("available", 1);
                        rs.updateRow();
                    }    
                
                   }
            
            
        } catch (SQLException ex) 
            {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    public void checkRewards(String rewardCode)
    {
        PreparedStatement ps;
        ResultSet rs;
        String query = "SELECT * FROM `rewards` WHERE `rewardCode` =?";
        
        try 
        {
            ps = MyConnection.getConnection().prepareStatement(query, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ps.setString(1, rewardCode);
            rs = ps.executeQuery();
            
            if(rs.next()) //if a record is found
            {
                int available = rs.getInt("available");
                int show_code = rs.getInt("show_code");
                int used = rs.getInt("used");
                int unlimited = rs.getInt("unlimited");
                String description = rs.getString(3);
                if (used == 1)
                {
                     jTextField_Results.setText( "Error: this reward code was already used by the customer." + rewardCode);
                }
                else if (available ==0 || show_code == 0)
                {
                     jTextField_Results.setText( "Error: this reward code should not be available to the customer." + rewardCode);
                }
                else if (available == 1 && show_code == 1 && used == 0 && unlimited == 0)
                    {
                        rs.updateInt("used", 1);
                        rs.updateRow();
                        //Need to add code for fresh bday reward here - for next version
                        jTextField_Results.setText("Reward code accepted! Please apply the following reward to the check: " + description);
                        
                    }
                else if (available ==1 && unlimited == 1)
                {
                    jTextField_Results.setText("Reward code accepted! Please apply the following reward to the check: " + description);
                }
                
                
            }
            else 
                { jTextField_Results.setText("Invalid code - Reward Code is not in our system.");}

            
        } catch (SQLException ex) 
            {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME_Staff_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME_Staff_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME_Staff_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME_Staff_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME_Staff_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Logout;
    private javax.swing.JButton jButton_Submit;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabel_Input;
    private javax.swing.JLabel jLabel_Results;
    public javax.swing.JLabel jLabel_Welcome;
    private javax.swing.JPanel jLabel_lower;
    private javax.swing.JPanel jPanel_upper;
    private javax.swing.JTextField jTextField_Input;
    private javax.swing.JTextField jTextField_Results;
    // End of variables declaration//GEN-END:variables
}
